languaje: node_js
node_js: 
   - 12.18.0
cache: yarn

install:
  - yarn install

script:
  - yarn run test
  - yarn run build 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
  

