languaje: node_js
install: travis_wait 30 mvn install
node_js: 
   - 12.18.0
cache: yarn

install:
  - yarn install

script:
  - yarn start
  - yarn test
  - yarn run build 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BACKEND_CONFIG 
  keep_history: true
  on:
    branch: backend_config




  

