languaje: node_js
install: travis_wait 5 mvn install
node_js: 
   - 12.18.0
cache: npm

install:
  - npm install

script:
  - npm start
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BACKEND_CONFIG 
  keep_history: true
  on:
    branch: backend_config
    




  

