languaje: node_js
install: travis_wait 5 install
node_js: 
   - 12.18.0
cache: yarn

install:
  - yarn install

script:
  - yarn test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BACKEND_CONFIG 
  keep_history: true
  on:
    branch: backend_config
    




  

