version: '3'

services:      
  jenkins:
    container_name: jenkins_blueocean
    image: jenkinsci/blueocean:latest
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./code/jenkins:/var/jenkins_home